name: SHA Pinning Demo Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  demo-unpinned:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install

  demo-version-pinned:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: false

  demo-outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  demo-third-party:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: some-random-user/suspicious-action@main
        with:
          config: dangerous
